In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [18]:
sent = [
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "Understand the meaning of words",
    "Your videos are good"
]

In [19]:
# Define the vocabulary size
voc_size = 10000

In [20]:
# OneHot Representation
onehot_rep = [one_hot(words, voc_size) for words in sent]
onehot_rep
    

[[9758, 1884, 8035, 3719],
 [9758, 1884, 8035, 7351],
 [9758, 8707, 8035, 8740],
 [7902, 2612, 5231, 6725, 9482],
 [7902, 2612, 5231, 6725, 2178],
 [7997, 9758, 32, 8035, 6272],
 [482, 3742, 3096, 6725]]

In [21]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
import numpy as np

In [23]:
sent_length = 8
embedded_docs = pad_sequences(onehot_rep, padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9758 1884 8035 3719]
 [   0    0    0    0 9758 1884 8035 7351]
 [   0    0    0    0 9758 8707 8035 8740]
 [   0    0    0 7902 2612 5231 6725 9482]
 [   0    0    0 7902 2612 5231 6725 2178]
 [   0    0    0 7997 9758   32 8035 6272]
 [   0    0    0    0  482 3742 3096 6725]]


In [24]:
# Feature Representation
dim = 10

In [27]:
model = Sequential()
model.add(Embedding(10000, dim, input_length=sent_length, input_shape=(sent_length,)))
model.compile('adam','mse')

c:\anaconda3\envs\imdb_env\Lib\site-packages\keras\src\layers\core\embedding.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [28]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[[ 0.04413015,  0.048686  ,  0.006501  , -0.02744819,
         -0.04518657,  0.02030418, -0.04457892,  0.03195561,
         -0.04405531,  0.00417024],
        [ 0.04413015,  0.048686  ,  0.006501  , -0.02744819,
         -0.04518657,  0.02030418, -0.04457892,  0.03195561,
         -0.04405531,  0.00417024],
        [ 0.04413015,  0.048686  ,  0.006501  , -0.02744819,
         -0.04518657,  0.02030418, -0.04457892,  0.03195561,
         -0.04405531,  0.00417024],
        [ 0.04413015,  0.048686  ,  0.006501  , -0.02744819,
         -0.04518657,  0.02030418, -0.04457892,  0.03195561,
         -0.04405531,  0.00417024],
        [ 0.04929603,  0.02197849, -0.01432655, -0.02270597,
         -0.03673823, -0.02676839,  0.02234468,  0.02094333,
          0.00256709,  0.03930967],
        [ 0.01717177, -0.04809495,  0.00635279,  0.03877095,
         -0.02381608,  0.00574363,  0.04001215,  0.03407898,
         -0.03609248, -0.0054876 ],
        [-0.01425738,  0.01909899, -0.0068404 ,  0.0

In [30]:
embedded_docs[0]

array([   0,    0,    0,    0, 9758, 1884, 8035, 3719], dtype=int32)

In [33]:
model.predict(embedded_docs[:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step


array([[[ 0.04413015,  0.048686  ,  0.006501  , -0.02744819,
         -0.04518657,  0.02030418, -0.04457892,  0.03195561,
         -0.04405531,  0.00417024],
        [ 0.04413015,  0.048686  ,  0.006501  , -0.02744819,
         -0.04518657,  0.02030418, -0.04457892,  0.03195561,
         -0.04405531,  0.00417024],
        [ 0.04413015,  0.048686  ,  0.006501  , -0.02744819,
         -0.04518657,  0.02030418, -0.04457892,  0.03195561,
         -0.04405531,  0.00417024],
        [ 0.04413015,  0.048686  ,  0.006501  , -0.02744819,
         -0.04518657,  0.02030418, -0.04457892,  0.03195561,
         -0.04405531,  0.00417024],
        [ 0.04929603,  0.02197849, -0.01432655, -0.02270597,
         -0.03673823, -0.02676839,  0.02234468,  0.02094333,
          0.00256709,  0.03930967],
        [ 0.01717177, -0.04809495,  0.00635279,  0.03877095,
         -0.02381608,  0.00574363,  0.04001215,  0.03407898,
         -0.03609248, -0.0054876 ],
        [-0.01425738,  0.01909899, -0.0068404 ,  0.0